#ifndef DIALOGUE_DATA_H
#define DIALOGUE_DATA_H

#include <stdbool.h>

#define DIALOGUE_CHARACTER_COUNT 20
#define DIALOGUE_TRIGGER_COUNT 17
#define DIALOGUE_VARIANTS_PER_TRIGGER 3
#define DIALOGUE_LANGUAGE_COUNT 8
#define DIALOGUE_UI_STRING_COUNT 122

#define DIALOGUE_LANGUAGE_ENGLISH 0
#define DIALOGUE_LANGUAGE_UKRAINIAN 1
#define DIALOGUE_LANGUAGE_GERMAN 2
#define DIALOGUE_LANGUAGE_POLISH 3
#define DIALOGUE_LANGUAGE_SPANISH 4
#define DIALOGUE_LANGUAGE_FRENCH 5
#define DIALOGUE_LANGUAGE_ITALIAN 6
#define DIALOGUE_LANGUAGE_PORTUGUESE 7

typedef enum {
    DIALOGUE_BAD_DRAW = 0,
    DIALOGUE_GOOD_DRAW,
    DIALOGUE_NPC_DEFENDED,
    DIALOGUE_NPC_TAKES,
    DIALOGUE_PLAYER_DEFENDED,
    DIALOGUE_PLAYER_TAKES,
    DIALOGUE_PLAYER_THROWS_ONE,
    DIALOGUE_PLAYER_THROWS_SEVERAL,
    DIALOGUE_PLAYER_THROWS_MANY,
    DIALOGUE_NPC_THROWS_ONE,
    DIALOGUE_NPC_THROWS_SEVERAL,
    DIALOGUE_NPC_STARTS_ATTACK,
    DIALOGUE_PLAYER_STALLING,
    DIALOGUE_PLAYER_LAST_CARD,
    DIALOGUE_NPC_LAST_CARD,
    DIALOGUE_NPC_WINS,
    DIALOGUE_NPC_LOSES
} DialogueTrigger;

bool dialogue_load_language(int language);
int dialogue_loaded_language(void);
const char* dialogue_get_ui_string(int language, int string_id);
const char* dialogue_get_line(int language, int character, int trigger, int variant);

#endif
